### ISSUE TITLE
API should validate uploaded asset metadata

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#100]
**Describe the bug**

When uploading a (potentially defunct) [component.yaml](https://github.com/romeokienzler/c3/raw/87e99aeb9e6864694ab7c02524086b3895aa795c/component.tar.gz) breaks UI. Uploading works but detail view on the component is empty

**To Reproduce**
- Upload this [component.yaml](https://github.com/romeokienzler/c3/raw/87e99aeb9e6864694ab7c02524086b3895aa795c/component.tar.gz) 
- Click on detail view of the component in the UI

**Expected behavior**

Detail view of component is showing up

**Environment**

 - OS: RHEL 8.x
 - Browser FF 89.0
 - MLX Version a913fd77d75771f25256785c7a9b1fc18f6f146d

**Comment by ckadner** [comment]
I will need to take a look at this. In a broader sense, the API should validate the uploaded template and reject malformed YAML or invalid metadata formats.

**Comment by ckadner** [comment]
Thanks to @drewbutlerbb4 for fixing part of the issue in PR #104 

I still need to add some code in the MLX API to validate the YAML structure and return a meaningful error message if something is not right.

Currently we show an error like this, if the YAML is missing required elements:

> `Upload Error: Please Retry - "TypeError: 'NoneType' object is not iterable" `

**Comment by ckadner** [comment]
@romeokienzler -- the component you attached here does not cause any errors for me (anymore?). Can you try again on the latest code base?

**Comment by drewbutlerbb4** [comment]
@ckadner #104 fixed the error that @romeokienzler was seeing for the UI.

> When uploading a (potentially defunct) component.yaml breaks UI.
I'm not sure if this component.yaml is invalid? If it is, it passes through the API instead of returning an error to the UI. I think that was @romeokienzler initial point.

**Comment by ckadner** [comment]
I did not see any errors in the API when I tried it. I had manufactured an error by altering the "inputs" field, to catch/fix the `Upload Error: 'NoneType' object is not iterable` e4145b2

**Comment by ckadner** [comment]
> @ckadner #104 fixed the error that @romeokienzler was seeing for the UI.
> 
> > When uploading a (potentially defunct) component.yaml breaks UI.
> 

@drewbutlerbb4 -- what error did you see there then?

**Comment by romeokienzler** [comment]
https://user-images.githubusercontent.com/5694071/123074964-0f8af280-d418-11eb-987e-0e3db7a8a6b1.mp4

I get the same behavior (see above)

**Comment by drewbutlerbb4** [comment]
@romeokienzler what is your setup here? Docker-compose? I can't reproduce this using the nightly build image with docker-compose setup

**Comment by ckadner** [comment]
> I get the same behavior (see above) on version/commit e4145b2

@romeokienzler -- in your video, I see the MLX UI still says:

> "Enter a name and upload a .tgz or .tar.gz file to **_create_** a new component". 

That was before Andrew's fix in PR #104 ([bb69575](https://github.com/machine-learning-exchange/mlx/commit/bb695751df3c54e47b3fb23eaddd63d0985921e7)). Now it should read:

> "Enter a name and upload a .tgz, .tar.gz, .**_yaml_** or .**_yml_** file to **_register_** a new component". 

Could you do a `docker compose pull` to get the latest nightly images to be pulled into your Docker Compose stack?

**Comment by romeokienzler** [comment]
@ckadner @drewbutlerbb4 sorry for the hassle - I did a "git pull" but no "docker-compose pull" - everything is working fine now, thanks a lot!
