### ISSUE TITLE
Minio dashboard no longer works in quickstart with Docker Compose 

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#133]
**Describe the bug**

**To Reproduce**

1. Follow the steps under [/quickstart](https://github.com/machine-learning-exchange/mlx/tree/main/quickstart)
2. Open the URL `localhost:9000` in a browser
3. See error in screenshot below
4. Warning in the `minio` service log

```
API: http://<my IP>:9000  http://127.0.0.1:9000 

Console: http://<my IP>:40843 http://127.0.0.1:40843 

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (40843), please use --console-address ":PORT" to choose a static port.

```

**Expected behavior**

Minio dashboard should open up

**Screenshots**

`localhost:9000/`

![image](https://user-images.githubusercontent.com/12246093/125528579-93adf4b0-796e-4abb-8c24-c94fc30ad3e5.png)

**Environment**

 - OS: macOS 10.15.6
 - Browser: Firefox, Chrome, Safari
 - MLX Version: f9a05ba

**Additional context**

https://github.com/minio/minio/issues/12660

**Comment by ckadner** [comment]
I need to update the [docker-compose.yaml](https://github.com/machine-learning-exchange/mlx/blob/main/quickstart/docker-compose.yaml) file with the Minio console port

**Comment by Tomcli** [comment]
FYI for kubernetes I'm using the kfp minio image for consistency. https://github.com/machine-learning-exchange/mlx/blob/main/manifests/read-only-k8s/minio.yaml#L48
