### ISSUE TITLE
Notebook launch fails with blank screen

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#147]
**Describe the bug**

Notebook launch fails with blank screen. Error on the web console:

```
"__init__() missing 2 required positional arguments: 'pipeline_name' and 'experiment_name'"
```

Debugging this problem, it seems to be raised by the `NotebookOp` class initialization.

https://github.com/machine-learning-exchange/mlx/blob/350c944f63d5a4581f1db219a3f2be241bedde26/api/server/swagger_server/code_templates/run_notebook.TEMPLATE.py#L26-L43

This change in kfp-notebook causes the error now:
https://github.com/elyra-ai/kfp-notebook/commit/21ebe68
https://github.com/elyra-ai/kfp-notebook/pull/83

**Comment by ckadner** [comment]
@Tomcli 
FYI @ptitzler :-)

**Comment by ckadner** [comment]
@ptitzler  -- for the missing arguments in our code template

- `pipeline_name` we use the same as in the `@dsl.pipeline(name=...` annotation? https://github.com/machine-learning-exchange/mlx/blob/350c944f63d5a4581f1db219a3f2be241bedde26/api/server/swagger_server/code_templates/run_notebook.TEMPLATE.py#L26-L27
-  `experiment_name` we use `NOTEBOOK_RUNS` like we define later in the code template https://github.com/machine-learning-exchange/mlx/blob/350c944f63d5a4581f1db219a3f2be241bedde26/api/server/swagger_server/code_templates/run_notebook.TEMPLATE.py#L68

**Comment by ptitzler** [comment]
That sounds like the right thing to do!

**Comment by ptitzler** [comment]
Asa side node, the https://github.com/elyra-ai/kfp-notebook repository will no longer be used starting Elyra 3.x. The code will be merged into the  https://github.com/elyra-ai/elyra repository by https://github.com/elyra-ai/elyra/pull/1918. We need to discuss the implications.

**Comment by ckadner** [comment]
@blublinsky
