### ISSUE TITLE
UI does not allow deleting assets

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#157]
**Describe the bug (or missing functionality)**

Currently, new assets can be registered using the MLX UI. Existing assets can be un-published and un-featured to effectively disappear, but there is no capability to delete registered assets (for admins).

@drewbutlerbb4

**Comment by ckadner** [comment]
@Tomcli

**Comment by ckadner** [comment]
@drewbutlerbb4 -- if you find some time, could you add a delete button on the VIEW ALL pages. Either delete button on every row, or, we would use the checkboxes in combination with a single delete button

**Comment by Zachary-Fernandes** [comment]
@ckadner I can work on this.
