### ISSUE TITLE
Introduce dynamic, hierarchical metadata for all assets

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#161]
**Is your feature request related to a problem? Please describe.**
Currently the number of attributes describing the assets are very limited

**Describe the solution you'd like**
dynamic (customizable), hierarchical metadata for all asset types would solve the issue of searching / sorting the assets.
Dynamic over static attributes has the advantage that without code changes. Hierarchies are important to group attributes / searches

**Describe alternatives you've considered**
Alternatively, on a asset level, metadata could be introduced, but this would require code changes for changing that metadata

**Comment by ckadner** [comment]
@romeokienzler -- could you distinguish this requirement from #167

**Comment by ckadner** [comment]
Closing this issue as a close relative (if not duplicate) of #167

Reopen and refine if there are use cases that cannot be addressed in #167
