### ISSUE TITLE
Setting assets published/featured is not reflected on featured assets page (UI caching issue)

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#171]
**Describe the bug**

Uploaded component can't be published/featured

**To Reproduce**
1. checkout 5422d23f1f2ea9297081d5b081e7197f196fc388
2. start "quickstart"
3. upload [component](https://github.com/romeokienzler/c3/blob/96112fab10c43f387ededf6abfadcc5393b40083/test_component.yaml) via [API](https://github.com/romeokienzler/c3/blob/96112fab10c43f387ededf6abfadcc5393b40083/src/mlx/publish.py)
4. Try to publish component - there is no save button - state change not reflected

**Expected behavior**

clicking the checkbox for publishing resulting in a status change or a (non existing) save button is expected

**Screenshots**

https://user-images.githubusercontent.com/5694071/127883731-36346b2c-9504-4b94-9bc4-9708bf493c14.mp4

**Environment**

 - OS: RHEL 8.3
 - Browser FF 90.0.2
 - MLX Version 5422d23f1f2ea9297081d5b081e7197f196fc388

**Comment by ckadner** [comment]
@romeokienzler -- can you try, if you open a new Private Window, your selection of featured/published assets should show correctly?

@drewbutlerbb4 -- I think this related to the recently added caching at the UI level. Could we add a switch to disable it?

**Comment by ckadner** [comment]
### Workarounds:

Either:
1. Open the MLX UI in a Private window -- a new window after each change like setting an asset published/featured
2. Delete the UI cache from you web browser developer console:
  Storage > key: `mlx-cache-http://localhost:8080/apis/v1alpha1/pipelines`

**Comment by romeokienzler** [comment]
@ckadner I confirm that opening a new private window or deleting the cache works as workaround

**Comment by ckadner** [comment]
I forgot @drewbutlerbb4 actually included a cache invalidation button in the admin settings

<img width="956" alt="Screen Shot 2021-08-02 at 5 05 15 PM" src="https://user-images.githubusercontent.com/12246093/127938154-71da7559-a76e-4e3d-b4cb-39217eb7c545.png">
