### ISSUE TITLE
Component detail view not rendering (wheel turning)

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#172]
**Describe the bug**

Component detail view not rendering (wheel turning)

**To Reproduce**
1. open component detail view

**Expected behavior**

detail view showing up

**Screenshots**

https://user-images.githubusercontent.com/5694071/127918262-d4255f8c-e448-48e9-b578-520ca69a7f13.mp4

**Environment**

 - OS: RHEL 8.3
 - Browser FF 90.0.2
 - MLX Version 5422d23f1f2ea9297081d5b081e7197f196fc388

**Comment by ckadner** [comment]
Our [mlexchange/mlx-api:nightly-main](https://hub.docker.com/r/mlexchange/mlx-api/tags?page=1&ordering=last_updated) and [mlexchange/mlx-ui:nightly-origin-main](https://hub.docker.com/r/mlexchange/mlx-ui/tags?page=1&ordering=last_updated) images had not been built and pushed to DockerHub during the past 3 weeks as we ran out of Travis credits. 

I just pushed both images with the latest code. Can you do a `docker compose pull` and try again?
