### ISSUE TITLE
Small navigation improvements

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#198]
Follow-up to #184

- [ ] let the "Join the Conversation" link sit at the bottom for non-admins, and push it up with the padding you have here for logged-in admins
- [ ] align the left side of the word "Conversation" with "Join" in the line above

_Originally posted by @ckadner in https://github.com/machine-learning-exchange/mlx/issues/184#issuecomment-910549650_

@drewbutlerbb4

**Comment by Prasantacharya** [comment]
I can work on this issue @ckadner
