### ISSUE TITLE
API should reject asset upload when `id` contain invalid characters 

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#209]
**Describe the bug**

For example, uploading a dataset YAML with `id: codenet_langclass` will cause issues when the PVC is created for that dataset later on, since Kubernetes resource IDs cannot contain underscore (`_`) characters (among others).

DataShim response when running the PVC mounting pipeline for a dataset with `id: codenet_langclass`:
```
HTTP response body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Dataset.com.ie.ibm.hpsys \"codenet_langclass\" is invalid: metadata.name: Invalid value: \"codenet_langclass\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
  "reason": "Invalid",
  "details": {
    "name": "codenet_langclass",
    "group": "com.ie.ibm.hpsys",
    "kind": "Dataset",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: \"codenet_langclass\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
        "field": "metadata.name"
      }
    ]
  },
  "code": 422
}
```

**Additional information:**

The actual `id` of the dataset asset in MLX was `codenet-langclass`, with correctly replaced underscore `_` character. However, the component generating the DataShim metadata used the original `id` field from the YAML file, with the `id` containing the underscore character.

FYI, here is a quick test of the `sanitize_k8s_name` function:

```Python
python -c "
from kfp_tekton.compiler._k8s_helper import sanitize_k8s_name; 
print(sanitize_k8s_name('under_score-dash'));
"
```
```
under-score-dash
```

**Proposed fix:**

Any `_upload_...` method in `api/server/swagger_server/controllers_impl/XXX_service_controller_impl.py` which takes an `id` (or similar field like `model_identifier`) from the uploaded YAML file to generate the asset `id` ...

api/server/swagger_server/controllers_impl/
- `dataset_service_controller_impl.py`, line 372: `def _upload_dataset_yaml(...)`
- `model_service_controller_impl.py`, line 381: `def _upload_model_yaml(...)`
- `notebook_service_controller_impl.py`, line 392: `def _upload_notebook_yaml(...)` (still being worked on #212)

... should call a new `validate_id()` method similar to the `swagger_server.controllers_impl.validate_parameters` function in `api/server/swagger_server/controllers_impl/__init__.py`:

```Python
def validate_id(id: str) -> (str, int):

    if id != sanitize_k8s_name(id)
        return f"Identifiers must contain lower case alphanumeric characters or '-' only.", 422

    return None, 200
```

**Comment by ckadner** [comment]
Related issue: CODAIT/exchange-metadata-converter#2

**Comment by vedantgannu** [comment]
I can look into this

**Comment by ckadner** [comment]
@vedantgannu -- I updated the description of this issue with more details and a proposed fix. Let me know if you have any questions. Thanks!
