### ISSUE TITLE
[UI] Move Copyright notice to bottom of page

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#215]
Currently the copyright notice is hanging out in the middle of the screen under the featured assets cards.

It would look better if those 2 lines could hug the bottom of the frame.

<img width="1382" alt="Screen Shot 2021-09-15 at 2 15 38 PM" src="https://user-images.githubusercontent.com/12246093/133510939-5b3efcf3-57be-4435-b1cf-124489cead01.png">

**Comment by BluThaitanium** [comment]
Checked out issue and PR'd
