### ISSUE TITLE
Selected assets show up selected across different menus

### ISSUE THREAD

**Issue by Zachary-Fernandes** [machine-learning-exchange/mlx#263]
**Describe the bug**

When someone selects some assets from one menu displaying all assets of one type and then enters a menu displaying all assets of a different type, it will say there are selected assets of that type when none are currently selected in that menu.

**To Reproduce**

The below steps use datasets and pipelines as example asset types, but this can occur across any asset types.

1. On the side bar, click "Datasets"
2. Toward the top of the page, click "VIEW ALL DATASETS"
3. Click the leftmost check boxes for some of the datasets
4. Note how many assets are selected with the line "Datasets (_n_ selected)" where _n_ is the number of datasets selected
5. On the side bar, click "Pipelines"
6. Toward the top of the page, click "VIEW ALL PIPELINES"
7. Notice the line "Pipelines (_n_ selected)" where _n_ is the number of datasets selected
8. Find none of the pipelines have checked boxes to the left of them

**Expected behavior**

When the user switches to a different asset page, they should see zero assets of that type selected.

**Screenshots**

Datasets menu:

![datasets](https://user-images.githubusercontent.com/32844805/142965307-f9f8098d-7d1f-4a6e-a6cc-5a7edfaaba67.PNG)

Pipelines menu:

![pipelines](https://user-images.githubusercontent.com/32844805/142965320-35ed9865-547c-41b4-9449-ef0ed105b706.PNG)

**Comment by ckadner** [comment]
Interesting observation @Zachary-Fernandes! Since you worked on this recently, did you find out why this happens? Some state that does not get cleared when navigating away from the page?

**Comment by JiaxuanYang** [comment]
@ckadner could you please assign this issue to me? thank you!
