### ISSUE TITLE
API Development with Docker Compose Shows Wrong UI Port

### ISSUE THREAD

**Issue by JAulet** [machine-learning-exchange/mlx#274]
**Describe the bug**

When following the api README for development and bringing up Docker Compose, it gives this message at the end:

```
no_api-mlx-ui-1      | [HPM] Proxy created: /  ->  http://mlx-api
no_api-mlx-ui-1      | Server listening at http://localhost:3000
```

This implies that you should go to http://localhost:3000 in your browser to view the UI when in reality, you must go to http://localhost:80

FYI @ckadner

**Comment by ckadner** [comment]
Good catch Joshua. Would you mind working on a fix?
