### ISSUE TITLE
Broken link and curl cmd in Kubernetes deployment prerequisites

### ISSUE THREAD

**Issue by rafvasq** [machine-learning-exchange/mlx#293]
Under [prerequisites](https://github.com/machine-learning-exchange/mlx/blob/main/docs/mlx-setup.md#prerequisites), the link to OpenShift cluster documentation is broken while the curl command returns `Not Found%`.

**Comment by ckadner** [comment]
Thanks Rafael, for identifying the dead link.

@Tomcli @yhwang -- I assume this should be the updated link to create OpenShift clusters on the IBM Cloud: https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_tutorial

**Comment by yhwang** [comment]
@ckadner your link is correct.
