### ISSUE TITLE
No IstioIngressGateway Route on Openshift

### ISSUE THREAD

**Issue by rafvasq** [machine-learning-exchange/mlx#347]
**Describe the bug**

The main README [states](https://github.com/machine-learning-exchange/mlx#2-access-the-mlx-ui):

> If you deployed using OpenShift, you can use IstioIngresGateway Route. You can find it in the OpenShift Console or using the CLI.
> `oc get route -n istio-system`

But no route is created, I end up accessing the MLX UI using one of the nodes' public IPs. 

      ❯ kubectl get node -o wide
      
      NAME            STATUS   ROLES           AGE     VERSION            INTERNAL-IP     EXTERNAL-IP       OS-IMAGE   KERNEL-VERSION                CONTAINER-RUNTIME
      10.87.171.224   Ready    master,worker   3h50m   v1.20.15+98b2293   10.87.171.224   169.62.122.24     Red Hat    3.10.0-1160.66.1.el7.x86_64   cri-o://1.20.8-3.rhaos4.7.gitb9df556.el7
      10.87.171.225   Ready    master,worker   3h51m   v1.20.15+98b2293   10.87.171.225   169.62.122.34     Red Hat    3.10.0-1160.66.1.el7.x86_64   cri-o://1.20.8-3.rhaos4.7.gitb9df556.el7
      10.87.200.79    Ready    master,worker   3h49m   v1.20.15+98b2293   10.87.200.79    150.238.130.173   Red Hat    3.10.0-1160.66.1.el7.x86_64   cri-o://1.20.8-3.rhaos4.7.gitb9df556.el7
      
      ❯ oc get route -n istio-system
      No resources found in istio-system namespace.

**Environment**

 - Openshift on IBM Cloud (ROKS) Versions 4.7, 4.8

@ckadner my thought is that if this is expected, then the documentation should be updated. Otherwise, I can look into the IstioIngressGateway route problem.

**Comment by ckadner** [comment]
Closed by #356
