### ISSUE TITLE
[CodeScan][Dashboard] Missing rate limiting 

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#42]
**Only project maintainers can see the details of this issue**

https://github.com/machine-learning-exchange/mlx/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmain

**Comment by ckadner** [comment]
@drewbutlerbb4

**Comment by drewbutlerbb4** [comment]
Fixed in: e93efb19a0ea9cf79c494d1bbe9dbf64ca6973ab
