### ISSUE TITLE
Travis should only build API or Dashboard image when respective code has changed

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#43]
From @Tomcli:

> ... we can leverage the script we have wrote for kfp-tekton. This way we don't need to build the image if the api/ui code hasn't changed

> https://github.com/kubeflow/kfp-tekton/blob/master/.travis.yml#L73-L95

_Originally posted by @Tomcli in https://github.com/machine-learning-exchange/mlx/issues/27#issuecomment-843456414_

**Comment by ckadner** [comment]
This is a good idea @Tomcli -- let me know if you want to add this? Otherwise I will create a PR for it.

**Comment by Tomcli** [comment]
I can put up something simple to start with. What we have in kfp-tekton is to check whether any source file in our dockerfiles has changed, if so run the docker build. You can update the script later on if you want to check for diff in a specific dockerfile.

**Comment by ckadner** [comment]
#45
