### ISSUE TITLE
MLX pipeline API schema doesn't work with Kubeflow 1.3

### ISSUE THREAD

**Issue by Tomcli** [machine-learning-exchange/mlx#50]
**Describe the bug**

When getting a list of pipelines from Kubeflow 1.3 using the MLX API. The server returns 500 with these errors
```
"The MySQL table 'mlpipeline.pipelines_extended' does not match Swagger class 'ApiPipelineExtended'.\n Found table with columns:\n  - 'UUID' varchar(255)\n  - 'CreatedAtInSec' bigint(20)\n  - 'Name' varchar(255)\n  - 'Description' longtext\n  - 'Parameters' longtext\n  - 'Status' varchar(255)\n  - 'DefaultVersionId' varchar(255)\n  - 'Namespace' varchar(63)\n  - 'Annotations' longtext\n  - 'Featured' tinyint(1)\n  - 'PublishApproved' tinyint(1).\n Expected table with columns:\n  - 'UUID' varchar(255)\n  - 'CreatedAtInSec' bigint(20)\n  - 'Name' varchar(255)\n  - 'Description' longtext\n  - 'Parameters' longtext\n  - 'Status' varchar(255)\n  - 'DefaultVersionId' varchar(255)\n  - 'Annotations' longtext\n  - 'Featured' tinyint(1)\n  - 'PublishApproved' tinyint(1).\n Delete and recreate the table by calling the API endpoint 'DELETE /pipelines_extended/*'"
```

**To Reproduce**

1. Deploy Kubeflow 1.3
2. Deploy MLX 
3. Go to the pipeline page, one of the apis will return 500 with the above error.

**Expected behavior**

**Screenshots**

**Environment**

 - MLX Version [e.g. 22]

**Additional context**

**Comment by ckadner** [comment]
I need to add the `namespace` property to the Pipeline API object

**Comment by ckadner** [comment]
@Tomcli -- do you know why the `namespace` attribute does not show up in the pipeline Swagger spec?

https://github.com/kubeflow/kfp-tekton/blame/master/backend/api/swagger/pipeline.swagger.json#L524-L572

or

https://github.com/kubeflow/pipelines/blame/master/backend/api/swagger/pipeline.swagger.json#L524-L572

**Comment by Tomcli** [comment]
They haven't update the swagger that much to keep the backward compatibility, but they did change the way to fetch pipelines for multi-user in kfp 1.5. See
https://github.com/kubeflow/kfp-tekton/blob/master/backend/src/apiserver/server/pipeline_server.go#L446-L472
