### ISSUE TITLE
UI to upload assets shows plural labels when singular is required

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#56]
> Enter ... create a new **_models_**

> **_Models name_**

<img width="987" alt="MLX upload Models" src="https://user-images.githubusercontent.com/12246093/119730255-5f32ca00-be2a-11eb-90b3-0e210829bffb.png">

same for the other asset upload pages

**Comment by ckadner** [comment]
thanks @ptitzler for finding this

**Comment by ckadner** [comment]
@drewbutlerbb4 -- can you give this one a shake as well? Thanks.

**Comment by ptitzler** [comment]
The PR does not address the issue in the label text:

![image](https://user-images.githubusercontent.com/13068832/121097667-35be5a80-c7a9-11eb-9e86-a07df177f7d4.png)

https://github.com/drewbutlerbb4/mlx/blob/4c229c82330082717b603c35000afe050c6f2884/dashboard/origin-mlx/src/pages/UploadPage.tsx#L144

**Comment by drewbutlerbb4** [comment]
Thanks @ptitzler didn't catch that. I'll append the change to my next PR
