### ISSUE TITLE
Remove api/swagger-codegen-cli-2.4.8.jar file

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#70]
The `swagger-codegen` CLI can be readily installed from external sources and need not be part of this repository.

> The JAR file `/api/swagger-codegen-cli-2.4.8.jar` appears to contain a large number of Java dependencies in binary form (approx. 7000 .class Java binary files). We recommend that LF projects should _not_ distribute binary files as part of their source code repositories. There are several reasons for this, including because it is harder for users of the source code repos to know about the provenance or contents of the binary files. In the presence of copyleft licenses these binaries might require sharing the corresponding source code.

> It is strongly recommended this JAR file be removed from the source code repo, and instead (if necessary) configuring the build system to retrieve it from an upstream location at build time / install time, as applicable. Or, alternatively, adjusting the documentation to instruct users where they can obtain these dependencies themselves, rather than distributing the binaries

Furthermore, the `swagger-cli` is not required for code generation. Only the `swagger-codegen` is required.
## Swagger Codegen 2.4.

We are using `swagger-codegen` version `2.4.x` to generate our API as `swagger-codegen`
version `3.0.x` no longer supports `python` (server) any longer.

Below are the instructions for installing the latest [`swagger-codegen` version `2.x`](https://formulae.brew.sh/formula-linux/swagger-codegen@2) using [Homebrew](https://docs.brew.sh/Installation). For installation on other platforms, go to [`swagger-api/swagger-codegen`](https://github.com/swagger-api/swagger-codegen#swagger-codegen-2x-master-branch) on GitHub.

**Note:** `swagger-codegen` `3.x` does not support the Python (server) anymore, so we need to downgrade to version `2.x` (`@2`):

    brew search swagger-codegen@
    brew install swagger-codegen@2
    brew link --force swagger-codegen@2

**Comment by ckadner** [comment]
FYI: @animeshsingh @Tomcli

**Comment by Tomcli** [comment]
We put that jar files for our interns because they were having issue using the swagger codegen from homebrew. I think swagger 2 is really old so it's hard for new developers to install the old codegen cli with the right settings.

**Comment by ckadner** [comment]
> We put that jar files for our interns because they were having issue using the swagger codegen from homebrew. I think swagger 2 is really old so it's hard for new developers to install the old codegen cli with the right settings.

    brew search swagger-codegen@
    brew install swagger-codegen@2
    brew link --force swagger-codegen@2

Did not work for you or Anessa? Can you elaborate on what did not work or what settings were not obvious or could not be adjusted? We have a script file wrapping the code generation which should take care of any settings or adjustments.

**Comment by Tomcli** [comment]
I think each macbook has different java and homebrew version. It's just hard to debug these kinds of env remotely. The issue we have last time is that the `brew install swagger-codegen@2` installed codgen 2.4.12+ which is not matching with the MLX schema we have.

**Comment by Tomcli** [comment]
If we can have instructions that install a pre-build binary (without homebrew etc), then we can make things more consistent.
