### ISSUE TITLE
instructions for how to install the java jar version of codegen.

### ISSUE THREAD

**Issue by Tomcli** [machine-learning-exchange/mlx#72]
@ckadner we probably need a set of instructions for how to install the java jar version of codegen. Homebrew and maven plugin might be too complicated and it may change based on the user's java/brew config.

_Originally posted by @Tomcli in https://github.com/machine-learning-exchange/mlx/issues/71#issuecomment-853293435_

**Comment by Tomcli** [comment]
I think this wget command can do the trick, but mac users need to install wget first
```
brew install wget

wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.8/swagger-codegen-cli-2.4.8.jar -O swagger-codegen-cli.jar
```

**Comment by ckadner** [comment]
@Tomcli -- The choice is **either** Homebrew **or** downloading the jar file. Maven should not be needed unless building the swagger-codegen jar from source is desired. 

Our instructions currently also link to the [`swagger-api/swagger-codegen`](https://github.com/swagger-api/swagger-codegen) on GitHub, which should provide the details on other install or build option. 

Did you want to copy this excerpt from there?

```Bash
# Download current stable 2.x.x branch (Swagger and OpenAPI version 2)
wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.10/swagger-codegen-cli-2.4.10.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar help
```
...and maybe add a command alias to make it compatible with the existing shell scripts we have:

```Bash
alias swagger-codegen="java -jar swagger-codegen-cli.jar"
```

**Comment by Tomcli** [comment]
yes, I think the swagger-codegen repo can be too confusing especially for junior developers. Also I remember 2.4.10 might change some schema on the MLX? I remember back then I have to downgrade the codegen-cli to 2.4.8 in order to not change some of the schema.

**Comment by Tomcli** [comment]
also the homebrew command is always installing the latest codegen 2.4.x (right now is 2.4.20). If we can't support that version then maybe we need to note it down.

**Comment by ckadner** [comment]
The latest `swagger-codegen@2` formula `2.4.20` from Homebrew works fine as well. Just tested it. 

Not sure what you may have experienced with respect to _"... `swagger-codegen` 2.4.12+ ... not matching with the MLX schema ..."_

**Comment by Tomcli** [comment]
When you run `./generate_code.sh`, it was generated some code differences. Is there any extra step we need to do?

**Comment by ckadner** [comment]
> When you run `./generate_code.sh`, it was generated some code differences. Is there any extra step we need to do?

Oh, yes, that's true. I added some fixes for that in previous commits and corrected the Git master branch reference to main in PR #59

**Comment by ckadner** [comment]
> When you run `./generate_code.sh`, it was generated some code differences. ... any extra step we need to do?

Yes. I had codified the required post-processing in the script `api/generate_code.sh` to undo the undesired codegen results, by doing a codegen before and after making changes to `api/swagger/swagger.yaml` and generating a reverse patch from the changes generated by running `codegen.sh` before having done any changes to the Swagger API spec.

I will do an evaluation of the various `swagger-codegen-cli.jar` version to see which version is best suited for regenerating the API server stubs without causing too many undesired code changes that need to be undone by post-processing the generated code.
