### ISSUE TITLE
Create KIND deployment option for MLX including KFP

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#73]
See _local cluster deployment_ options for Kubeflow Pipelines at https://www.kubeflow.org/docs/components/pipelines/installation/localcluster-deployment/. 

The MLX API and UI should _simply_ be deployed on top of that. Easy as pie 😄 🍰

**Comment by ckadner** [comment]
@sabary661990615

**Comment by Tomcli** [comment]
FYI non org members only can self assign issues.

**Comment by ckadner** [comment]
FYI @romeokienzler -- Yash is working on a KIND deployment option for MLX
