### ISSUE TITLE
[ui] The experiments iframe contains kubeflow namespace selector banner

### ISSUE THREAD

**Issue by yhwang** [machine-learning-exchange/mlx#77]
The experiments iframe points to `/_/pipeline/?ns=mlx#/experiments` which contains the whole experiments view from kubeflow dashboard. The original `/pipeline/#/experiments` doesn't work since kfp v.13. The original link can't get correct namespace information and fails to show the experiments.   

**To Reproduce**

1. Go to mlx dashboard
2. Login as admin user
3. Click on `Pipelines` and Select `View Experiments`
4. The iframe shows the kubeflow experiments view which contains the namespace selector

**Expected behavior**

Only show the experiments views without kubeflow namespace selector and nav bar.

**Comment by drewbutlerbb4** [comment]
Just to make sure I understand, the issue here is that you would like to remove the namespace selector banner that is displayed in the experiments iframe?

**Comment by yhwang** [comment]
yes, correct. and when you click on the three horizontal line icon (on the very left of the namespace selector), it shows you the kubeflow nav menu. basically, for now, using ` /_/pipeline/?ns=mlx#/experiments`, it includes the whole kubeflow dashboard.
