### ISSUE TITLE
Single user pipeline run is having error

### ISSUE THREAD

**Issue by Tomcli** [machine-learning-exchange/mlx#91]
**Describe the bug**
When running single user MLX, the pipeline run is returning the below errors:
```
"Error while trying to run pipeline bdddf286-4c26-46b8-9af5-d08aafc2ce1d: 'MaxRetryError' object has no attribute 'body'"
```

However, for component, model, dataset, notebook runs, the pipeline run works fine.

**To Reproduce**
Install kustomize 3.2.1
```shell
git clone https://github.com/machine-learning-exchange/manifests -b mlx-single-user
cd manifests
# run the below command two times if the CRDs take too long to provision.
kustomize build example | kubectl apply -f -
```
Go to <public_ip>:30380/mlx, publish the default pipeline in the view all pipelines and run it. You will see a blank page because the API is returning the above error.

**Expected behavior**

**Screenshots**

**Environment**

 - MLX Version [e.g. 22]

**Additional context**

**Comment by ckadner** [comment]
@Tomcli -- on your single-user cluster I get this error when trying to create (or get) an experiment:

```
Invalid input error: In single-user mode, ListExperiment cannot filter by namespace.
```

This happens regardless of setting the namespace to `None`, `""`, leaving the parameter out, since the KFP client will default to populate the `kubeflow` namespace in it's own call to the KFP server API to `get_experiment`.

@yhwang -- I am getting this error (from outside the cluster) multi-user:

```
Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.
Failed to authorize with API resource references
```

**Comment by Tomcli** [comment]
@ckadner so I use the KFP-Tekton 0.8.1 SDK to run pipelines on single user mode. If you follow this instruction it should able to submit the pipeline with the `run_pipeline` function.
https://github.com/kubeflow/kfp-tekton/tree/master/guides/kfp-user-guide#2-run-pipelines-using-the-kfp_tektontektonclient-in-python

**Comment by ckadner** [comment]
@Tomcli -- the MLX API deployed on your single-user cluster is still trying to use the `ml-pipeline-ui` service. I will switch to using the `ml-pipeline` service, or, rather I will let KFP Client figure that out.

**Comment by Tomcli** [comment]
@ckadner as long as the API is able to run pipelines, it doesn't really matter how you provision the client. But I do recommend to use the `ml-pipeline` service endpoint if we want to keep things consistent.

**Comment by Tomcli** [comment]
you can add a flag during deployment time to tell whether MLX is deployed with single user or multi-user KFP. I will update the manifest accordingly.

**Comment by yhwang** [comment]
For the error in multi-user env, I guess the solution is that mlx-api pod needs to carry the `kubeflow-userid` header when calling ml-pipeline APIs. can you try out this mlx-ui image: `yihongwang/mlx-ui:dev`?
In that image, I injected the `kubeflow-userid` header into the request at the proxy middleware.

**Comment by yhwang** [comment]
@ckadner I checked the code in both `ml-pipeline-ui` and `ml-pipeline`. For `ml-pipeline-ui`, it just forwards the apis calls to `ml-pipeline` which contain `kubeflow-userid` header for user id. For `ml-pipeline`, it uses two authenticators to retrieve user id:
- http_header: uses `kubeflow-userid` header
- token_review: uses `authorization` header

So the bottom line is you have to pass `kubeflow-userid` header to `ml-pipeline`. However, I don't know how can you do that by using the kfp.Client().
