### ISSUE TITLE
UI enforces .tgz or .tar.gz upload file formats where .yaml is supported by API

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#94]
@drewbutlerbb4 -- in the MLX API, assets can be uploaded using either `.tgz`/`.tar.gz` file formats or `.yaml`/`.yml` files, as well as URLs pointing to files in either of those formats.

Do you know why/where the UI enforces `.tgz`/`.tar.gz` upload formats?

**Comment by ckadner** [comment]
@romeokienzler

**Comment by ckadner** [comment]
Once we clarify, and/or make changes in the UI we also need to update our READMEs that describe the upload for all respective asset types

**Comment by drewbutlerbb4** [comment]
I probably overlooked it or maybe it didn't get passed down to me. I don't think there is a reason why we should not accept yamls in the UI

**Comment by ckadner** [comment]
@drewbutlerbb4 when you get a chance to tackle this, please also enable the `/{asset-type}/upload_from_url`
